In [1]:
import numpy as np

#### EXERCISE 14 
Array Generation of random integers within a specified range

Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)

In [38]:
np.random.seed(123) 
x = np.random.randint(0,10,(5,5))
print(x)


[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


#### EXERCISE 15
Array Generation of random numbers following normal distribution

Output a 3-by-3 array of random numbers following normal distribution

In [43]:
np.random.seed(123)
arr = np.random.normal(size = (3,3))
print(arr)

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]
 [-2.42667924 -0.42891263  1.26593626]]


#### EXERCISE 16 
Matrix Multiplication

Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

In [55]:
arr_1 = np.array([[1,2], 
                 [3,5]])

arr_2 = np.array([[2,4],
                  [3,4]])

#1
x = arr_1.dot(arr_2)
print(x)
print("---------")
#2
y = np.matmul(arr_1, arr_2)
print(y)
print("---------")
#3
z = arr_1 @ arr_2
print(z)


[[ 8 12]
 [21 32]]
---------
[[ 8 12]
 [21 32]]
---------
[[ 8 12]
 [21 32]]


#### EXERCISE 17
Matrix Transpose

Output the transpose of a matrix (as numpy array)

In [65]:
arr = np.arange(20).reshape(5,4)
tr = arr.transpose()
# print(tr)

arr2 = np.arange(20).reshape(5,2,2)

x = arr2.transpose()
print(x)

[[[ 0  4  8 12 16]
  [ 2  6 10 14 18]]

 [[ 1  5  9 13 17]
  [ 3  7 11 15 19]]]
