In [22]:
import numpy as np

#### EXERCISE 1 
 Element-wise addition of 2 numpy arrays
 
Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

In [2]:
array_1 = np.array([[1,2,3],
                    [4,5,6]])

array_2 = np.array([[7,8,9],
                    [6,5,4]])

sum = array_1 + array_2
print(sum)

[[ 8 10 12]
 [10 10 10]]


#### EXERCISE 2 
Multiplying a matrix (numpy array) by a scalar

Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?

In [4]:
arr = np.array([[7,6,5,8],
                [5,7,9,7]])

arr_2x = arr * 2

print(arr_2x)

[[14 12 10 16]
 [10 14 18 14]]


#### EXERCISE 3 
Identity Matrix

Create an identity matrix of dimension 4-by-4

In [12]:
#1
array2D = np.arange(0,16).reshape(4,4)

row_count , column_count = array2D.shape 
for i in range(row_count):
  for j in range(column_count):
    if i == j: 
      array2D[i,j] = 1
    else:
      array2D[i,j] = 0

print(array2D)
print("-----------")
#2 
i = np.eye(4, dtype="int32")
print(i)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
-----------
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


#### EXERCISE 4 
Array re-dimensioning

Convert a 1-D array to a 3-D array

In [14]:
temp = np.arange(0,27)
arr = temp.reshape((3,3,3))

print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


#### EXERCISE 5 
Array datatype conversion

Convert all the elements of a numpy array from float to integer datatype

In [17]:
temp = np.array([[1.5,4.5,8.0], 
                [7.2,6.3,9.1]])
arr = temp.astype("int")

print(arr)

[[1 4 8]
 [7 6 9]]


#### EXERCISE 6 
Obtaining Boolean Array from Binary Array

Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array

In [21]:
first_arr = np.eye(3)
sec_arr = first_arr.astype(bool)
print(sec_arr)

[[ True False False]
 [False  True False]
 [False False  True]]
