In [2]:
import numpy as np

#### EXERCISE 7 
Horizontal Stacking of Numpy Arrays
Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays)

In [5]:
#1
arr_1 = np.array([[1,2],
                  [3,4]])
arr_2 = np.array([[3,4],
                  [5,6]])

concat = np.concatenate([arr_1, arr_2], axis = 1)
print(concat)
print("-------------")
#2 
x = np.hstack((arr_1, arr_2))
print(x)


[[1 2 3 4]
 [3 4 5 6]]
-------------
[[1 2 3 4]
 [3 4 5 6]]


#### EXERCISE 8 
Vertically Stacking of Numpy Arrays

Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays)

In [8]:
#1
arr_1 = np.array([[1,2],
                  [3,4]])
arr_2 = np.array([[5,6],
                  [7,8]])

x = np.concatenate([arr_1, arr_2])

print(x)
print("********")

#2 

y = np.vstack((arr_1, arr_2))
print(y)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
********
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### EXERCISE 9 
Custom Sequence Generation

Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

In [5]:
#1 
x = np.arange(0,100,2)
print(x)

# 2
number_list = [x for x in range(0, 101, 2)]
y = np.array(number_list)

print(y)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


#### EXERCISE 10 
Getting the positions (indexes) where elements of 2 numpy arrays match

From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [7]:
a = np.array([1,2,3,4,5])

b= np.array([1,4,3,7,5])

print(np.where(a == b))


(array([0, 2, 4], dtype=int64),)


#### EXERCISE 11
Generation of given count of equally spaced numbers within a specified range

Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)

In [8]:
a = np.linspace(0,100,5)
print(a)

[  0.  25.  50.  75. 100.]


#### EXERCISE 12 
Matrix Generation with one particular value.

Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

In [11]:
#1
arr = np.full((2,3),5)
print(arr)

#2 
print("*********")

a = np.ones((2, 3), dtype= "int")
b = 5*a
print(b)



[[5 5 5]
 [5 5 5]]
*********
[[5 5 5]
 [5 5 5]]


#### EXERCISE 13 
Array Generation by repeatition of a small array across each dimension

Output an array by repeating a smaller array of 2 dimensions, 10 times

In [16]:
arr = np.array([[1,2],
                [3,4]])

last_arr = np.tile(arr,10)
print(last_arr)

[[1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4]]
