In [2]:
import numpy as np

### Soru 1
* 30 ile 70 arasındaki sayıları içeren bir array oluşturunuz. 
* Oluşturduğunuz array'i 4x5x2 şekline çeviriniz.
* Oluşturduğunuz array'in son boyutundaki elemanların ilkini yazdırınız. Örnek çıktı; \
[[30 32 34 36 38]\
 [40 42 44 46 48]\
 [50 52 54 56 58]\
 [60 62 64 66 68]]

In [26]:
arr = np.arange(30,70).reshape(4,5,2)
print(arr[:4, :5, 0])


[[30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]]


### Soru - 2
- Kullanicidan sirasiyla `adi, soyadi, yasi ve yasadigi sehrin plaka kodu` inputlarini alip bunlari 2x2 formatinda bir array'e cevirin. Ornek cikti su sekilde olmali:

```python
# array([['Arzu', 'Asya'],
#        ['27', '35']], dtype='<U1')
```

In [36]:
name = (input("Adınızı girin:"))
surname = (input("Soyad girin:"))
age = int(input("Yas girin:"))
city = int(input("Plaka girin:"))

info = np.array([name, surname, age, city]).reshape(2,2)
print(info)



[['ece' 'kara']
 ['28' '35']]


### Soru - 3
- Alttaki kodu calistirdiginizda 3 boyutlu ve tamami sifirlardan olusan bir array elde edeceksiniz. Bu arrayin ciktisini altta belirtilen hedef ciktiya donusturmek icin gerekli basamaklari kurgulayiniz.
```python
zeros = np.array([np.zeros(10), np.zeros(10), np.zeros(10)], ndmin = 3)
zeros

In [46]:
zeros = np.array([np.zeros(10), np.zeros(10), np.zeros(10)], ndmin = 3)


zeros[0,0:3:2,0:10:2] = 1
zeros[0,1,1:10:2] = 1
print(zeros)



[[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
  [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]]


### Soru 4
Verilen array'i birim matrise çeviren bir fonksiyon yazınız.

array2D = np.arange(0,25).reshape(5,5)

In [48]:
array2D = np.arange(0,25).reshape(5,5)

row_count, column_count = array2D.shape

for i in range(row_count):
    for j in range(column_count):
        if i == j:
            array2D[i,j] = 1
        else: 
            array2D[i,j] = 0
            
print(array2D)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### Soru 5
* 0 ile 500 arasındaki 5'in katı olan sayılardan bir array oluşturunuz.
* Oluşturduğunuz array'i 3 boyutlu herhangi bir array'e çeviriniz.Örnek olarak: 2x5x10, 4x5x5, 1x10x10 gibi arrayler olabilir.
* Oluşturduğunuz array'in indexlerini tek tek gezerek 6'ya tam olarak bölünen değerleri bulunuz.

In [ ]:
arr = np.arange(0,500,5).reshape(4,5,5)
row_count, column_count, depth = arr.shape

for i in range(row_count):
    for j in range(column_count):
        for k in range(depth):
            value = arr[i,j,k]
            if value % 6 == 0 and value != 0:
                print(arr[i,j,k])

### Soru 6

 Bir arama fonksiyonu yazınız ve parametre olarak bir array ve aranan değeri alınız. Aranan değer array içerisinde bulunuyorsa bulunduğu index'i, bulunmuyorsa '-1' değerini döndürünüz. Bu fonksiyonu sadece 3 boyutlu arrayler için yazınız.

In [56]:
def search(arr, value):
    row_count, column_count, depth = arr.shape
    
    for i in range(row_count):
        for j in range(column_count):
            for k in range(depth):
                if arr[i,j,k] == value:
                    return i,j,k

array_3d = np.arange(0, 500, 5)
resize = array_3d.reshape(4,5,5)
print(search(resize, 20))


(0, 0, 4)
